Resources:
  HangmanFrontPublicS3Bucket:                                                       
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: hangmanfront.dev.endava.com
      WebsiteConfiguration:
        ErrorDocument: 'index.html'
        IndexDocument: 'index.html'
      Tags: 
        - Key: owner
          Value: dacevedo

  HangmanFrontPublicS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref HangmanFrontPublicS3Bucket #required
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: s3:PutObject
          Resource: arn:aws:s3:::hangmanfront.dev.endava.com/*
        - Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: arn:aws:s3:::hangmanfront.dev.endava.com/*
          